In [ ]:
# How to create:
# 1. Vector by numpy
# 2. Matrix by numpy
# 3. Shape of a matrix by numpy (dimension)
# 3. Matrix of zeroes with numpy
# 4. Matrix transpose by numpy
# 5. Matrix multiplication by numpy
# 6. Matrix psuedo inverse or inverse by numpy
# 7. Norm of matrix by numpy

In [ ]:
import numpy as np
#creating a 1-D list (horizontal)
list1 = [1, 2, 3]
#creating a 1-D list (vertical)
list2 = [[10],
          [20],
          [30]]
#creating a vector1
#vector as row
vector1 = np.array(list1)
#creating a vector as vector2
#vector as column
vector2 = np.array(list2)
#showing horizontal vector
print("horizontal vector")
print(vector1)
#showing vertical vector
print("vertical vector")
print(vector2)

horizontal vector
[1 2 3]
vertical vector
[[10]
 [20]
 [30]]


In [ ]:
#creat a matrix
a = np.matrix([[1,2],[3,4],[5,6],[7,8]])
print(a.shape)

(4, 2)


In [ ]:
a=np.matrix([[7,8,9],[10,11,12],[1,2,3]])
print(a.shape)

(3, 3)


In [ ]:
np.zeros((6,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#matrix transpose
a=np.array([[1,2],[3,4]])
np.transpose(a)

b=np.array([[4,5],[7,8],[9,10]])
np.transpose(b)

array([[ 4,  7,  9],
       [ 5,  8, 10]])

In [ ]:
#matrix multiplication
m1=np.array([[1,2],[3,4],[5,6]])
m2=np.array([[7,8],[9,10]])
m3=np.dot(m1,m2)
print(m3)

[[ 25  28]
 [ 57  64]
 [ 89 100]]


In [ ]:
m1=([[1,2,3],[4,5,6]])
m2=([[1,2],[3,4],[5,6]])
m3=np.dot(m1,m2)
print(m3)

[[22 28]
 [49 64]]


In [ ]:
m1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(m1.shape)

(3, 3)


In [ ]:
print(m1)
print(m2)

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]]


In [ ]:
#how to psedoinverse a matrix
np.linalg.pinv(m1)


matrix([[-6.38888889e-01, -1.66666667e-01,  3.05555556e-01],
        [-5.55555556e-02,  1.30136518e-16,  5.55555556e-02],
        [ 5.27777778e-01,  1.66666667e-01, -1.94444444e-01]])

In [ ]:
#norm of matrix
np.linalg.norm(m1)

16.881943016134134

In [ ]:
import pandas as pd
DF = pd.read_csv('/Users/aidarezaei/Desktop/Desktop/CV/CV/data.csv')
X = DF.values